swagger: '2.0'
info:
  description: Personal Goals
  version: 0.9.1
  title: Personal Goals
  contact:
    email: lukas.slizik@gmail.com

  license:
    name: todo
    url: todo

paths:
  /activities:
    get:
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/Activity'
  /activities/{activityId}:
    get:
      parameters:
      - in: query
        name: activityId
        required: true
        type: string
        format: guid
      responses:
        200:
          schema:
            $ref: '#/definitions/Activity'
  /activities/{activityId}/goals:
    get:
      parameters:
      - in: query
        name: activityId
        required: true
        type: string
        format: guid
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/Goal'
  /activities/{activityId}/goals/{goalId}:
      get:
        parameters:
        - in: query
          name: activityId
          required: true
          type: string
          format: guid
        - in: query
          name: goalId
          required: true
          type: string
          format: guid
        responses:
          200:
            schema:
              $ref: '#/definitions/Goal'

  /activities/{id}/goals/{goalId}/achievments:
    get:
      parameters:
        - in: query
          name: activityId
          required: true
          type: string
          format: guid
        - in: query
          name: goalId
          required: true
          type: string
          format: guid

      responses:

  /activities/{id}/goals/{goalId}/achievments/{achievmentId}:

definitions:
  Activity:
    type: object
    properties:
      id:
        type: string
        format: guid
      name:
        type: string
      description:
        type: string
  Goal:
    type: object
    properties:
      id:
        type: string
        format: guid
      target:
        type: number
        format: int32
      step:
        type: number
        format: int32
      unit:
        type: string
      multiplicator:
        type: number
        format: float
  TimePeriod:
    type: object
    properties:
      id:
        type: string
        format: guid
      from:
        type: string
        format: date
      to:
        type: string
        format: date
  Achievment:
    type: object
    properties:
      id:
        type: string
        format: guid
      points:
        type: number
        format: float
      timePeriod:
        type: object
        $ref: '#/definitions/myElement'


# Added by API Auto Mocking Plugin
host: todo
basePath: todo
schemes:
 - http